MODE = "REAL"
PLANT = "tomato"

LOG_PATH = "data/real_log.csv"
READ_INTERVAL_SECONDS = 300

TZ_OFFSET_HOURS = 2

SOIL_PORT = "/dev/ttyUSB0"
SOIL_BAUDRATE = 9600
SOIL_SLAVE_ID = 1

VWC_FIELD_CAPACITY = None
LUX_TO_PAR = 0.0185